name: build-clang

on: [push, pull_request, workflow_dispatch]

jobs:
  build-clang:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        build-type: [Release, Debug]
        int64: [HIGHSINT64=ON, HIGHSINT64=OFF]
        fast-build: [FAST_BUILD=OFF]

    steps:
      - uses: actions/checkout@v4

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}-${{ matrix.os }}-${{ matrix.build-type }}-${{ matrix.fast-build}}-${{ matrix.int64 }}

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake $GITHUB_WORKSPACE \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -D${{ matrix.fast-build }} -D${{ matrix.int64 }}

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: |
          export CC=clang
          export CC=clang++
          cmake --build . --parallel --config ${{ matrix.build-type }}

      - name: Test
        working-directory: ${{runner.workspace}}/build
        shell: bash
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest --parallel 2 --timeout 300 --output-on-failure -C ${{ matrix.build-type }}
