name: build-mingw

on: [push, pull_request]

jobs:
  mingw:
    runs-on: windows-latest

    defaults:
      run:
        # Use MSYS2 as default shell
        shell: msys2 {0}

    strategy:
      matrix:
        msystem: [MINGW64, UCRT64, CLANG64]
        build-type: [Release, Debug]
        int64: [HIGHSINT64=ON, HIGHSINT64=OFF]
        fast-build: [FAST_BUILD=ON, FAST_BUILD=OFF]
        include:
          - msystem: MINGW64
            target-prefix: mingw-w64-x86_64
          - msystem: UCRT64
            target-prefix: mingw-w64-ucrt-x86_64
          - msystem: CLANG64
            target-prefix: mingw-w64-clang-x86_64
        exclude:
          - fast-build: On
            int64: On

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          install: >-
            base-devel
            ${{ matrix.target-prefix }}-cmake
            ${{ matrix.target-prefix }}-cc
            ${{ matrix.target-prefix }}-ninja

      - uses: actions/checkout@v3

      - name: Configure CMake
        run: |
          mkdir build && cd build
          cmake .. -DHIGHS_NO_DEFAULT_THREADS=ON \
            -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -D${{ matrix.fast-build }} -D${{ matrix.int64 }}

      - name: Build
        run: |
          cd build && cmake --build . --parallel --config ${{ matrix.build-type }}

      - name: Test
        run: cd build && ctest --parallel 2 --timeout 300 --output-on-failure -C ${{ matrix.build-type }}
